[package]
name = "todo_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
rocket = "0.4.11"
serde = "1.0.152"
surrealdb = "1.0.0-beta.8"
thiserror = "1.0.39"
tokyo = "1.0.0"
